query GetProductDetailForDesign($id: ID!, $channel: String!) {
    product(id: $id, channel: $channel) {
      id
      name
      variants {
        id
        name
        sku
        product{
          id
        }
        attributes {
          attribute {
            id
            name
            slug
          }
          values {
            id
            name
            slug
            value
          }
        }
        metadata {
          key
          value
        }
        media {
          id
          alt
          url(format: WEBP, size: 1080)
        }
        pricing {
          price {
            gross {
              amount
              currency
            }
            net {
              amount
              currency
            }
          }
        }
      }
    }
  }