fragment OrderDetails on Order {
	id
	discounts {
		type
		name
		translatedName
		valueType
		value
		amount {
			currency
			amount
		}
	}
	number
	created
	total {
		gross {
			amount
			currency
		}
	}
	lines {
		metadata {
			key
			value
		}
		variant {
			id
			name
			media {
				url
				alt
			}
			product {
				id
				name
				description
				slug
				category {
					id
					name
				}
			}
			pricing {
				price {
					gross {
						amount
						currency
					}
				}
			}
		}
		quantity
	}
	paymentStatus
}
